language: node_js
node_js:
  - "stable"


services:
  - docker

before_install:
  - docker build -t vikashraj1825/docker-vite -f Dockerfile.dev .

script:
  - docker run vikashraj1825/docker-vite npm run test -- --coverage
